'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Nav & Sidebar
    dashboard: 'Dashboard',
    users: 'Users',
    user: 'User',
   
    no_users_found: 'No users found',
    wallet: 'Wallet',
    therapists: 'Therapists',
    therapist: 'Therapist',
    orders: 'Orders',
    services: 'Services',
    vouchers: 'Vouchers',
    total_vouchers: 'total vouchers',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    pijat_admin: 'Pijat Admin',
    on_demand_platform: 'On-Demand Platform',

    // Common Buttons & Actions
    save_changes: 'Save Changes',
    add_new: 'Add New',
    add_therapist: 'Add Therapist',
    add_service: 'Add Service',
    add_voucher: 'Add Voucher',
    update_therapist: 'Update Therapist',
    update_service: 'Update Service',
    update_voucher: 'Update Voucher',
    update: 'Update',
    total_orders_count: 'total orders',
    auto_refresh: 'Auto-refresh every 5s',
    all: 'All',
    orders_monitor: 'Orders Monitor',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    refresh: 'Refresh',
    search: 'Search',
    all_status: 'All Status',
    filter: 'Filter',

    // Table Headers & Content
    name: 'Name',
    phone: 'Phone',
    email: 'Email',
    gender: 'Gender',
    status: 'Status',
    actions: 'Actions',
    rating: 'Rating',
    date: 'Date',
    registered: 'Registered',
    amount: 'Amount',
    customer: 'Customer',
    verified: 'Verified',
    bio: 'Bio',
    skills: 'Skills',
    device_id_label: 'Device ID',
    active_status: 'Active Status',
    therapist_detail: 'Therapist Detail',
    no_skills: 'No specific skills',
    close: 'Close',
    no_therapists: 'No therapists found',
    showing: 'Showing',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',

    // Form Labels
    full_name: 'Full Name',
    phone_number: 'Phone Number',
    email_address: 'Email Address',
    brief_description: 'Brief Description',
    verify_immediately: 'Verify this therapist immediately',
    female: 'Female',
    male: 'Male',

    // Status Labels
    online: 'Online',
    offline: 'Offline',
    busy: 'Busy',
    pending: 'Pending',
    accepted: 'Accepted',
    on_the_way: 'On The Way',
    in_progress: 'In Progress',
    completed: 'Completed',
    cancelled: 'Cancelled',
    rejected: 'Rejected',

    // Dashboard Overview
    total_orders: 'Total Orders',
    active_therapists: 'Active Therapists',
    new_users: 'New Users',
    recent_orders: 'Recent Orders',
    no_orders_yet: 'No orders yet',
    quick_actions: 'Quick Actions',
    vs_last_month: 'vs last month',
    real_time_overview: 'Real-time overview of your platform',
    total_revenue: 'Total Revenue',
    total_users: 'Total Users',
    total_therapists: 'Total Therapists',
    active_orders: 'Active Orders',
    online_therapists: 'Online Therapists',
    todays_orders: 'Todays Orders',
    todays_revenue: 'Todays Revenue',
    x_today: 'today',
    x_online: 'online',
    platform_performance: 'Platform performance analytics',
    daily_revenue: 'Daily Revenue (Last 30 Days)',
    daily_orders: 'Daily Orders (Last 30 Days)',
    status_breakdown: 'Order Status Breakdown',
    services_configured: 'services configured',
    edit_service: 'Edit Service',
    service_name: 'Service Name',
    duration_min: 'Duration (minutes)',
    price_idr: 'Harga (IDR)',
    is_active_label: 'Service is',
    active: 'Active',
    inactive: 'Inactive',
    saving: 'Saving...',
    service_updated: 'Service updated!',
    service_created: 'Service created!',
    delete_confirm: 'Delete this item?',
    failed_to_delete: 'Failed to delete',
    edit_voucher: 'Edit Voucher',
    voucher_code: 'Voucher Code',
    voucher_type: 'Voucher Type',
    percentage: 'Percentage',
    fixed_amount: 'Fixed Amount',
    discount_value: 'Discount Value',
    min_order: 'Min Order Amount',
    direct: 'Direct Discount',
    new_user: 'New User Only',
    repeat_order: 'Repeat Order',
    happy_hour: 'Happy Hour',
    location: 'Location Based',
    user_tier: 'User Tier',
    cashback: 'Cashback',
    wallet_balance: 'Wallet Balance',
    registered_date: 'Registered Date',
    therapist_level: 'Therapist Level',
    account_status: 'Account Status',
    skills_specialization: 'Skills & Specializations',
    short_bio: 'Short Bio',
    voucher_updated: 'Voucher updated!',
    voucher_created: 'Voucher created!',
    revenue: 'Revenue',
    unlimited: 'Unlimited',
    no_cap: 'No cap',
    type: 'Type',
    manage_service_types: 'Manage Service Types',
    add_service_type: 'Add New Service Type',
    list_service_types: 'Service Type List',
    service_type_desc: 'Manage service categories and pricing models',
    edit_service_type: 'Edit Service Type',

    // Settings
    general: 'General',
    language: 'Language',
    platform_name: 'Platform Name',
    support_email: 'Support Email',
    commission_rate: 'Commission Rate (%)',
    notifications: 'Notifications',
    security: 'Security',
    integrations: 'Integrations',
    verify_therapist: 'Verify Therapist',
    not_verified: 'Not Verified',
    tier: 'Tier',
    bronze: 'Bronze',
    silver: 'Silver',
    gold: 'Gold',
    diamond: 'Diamond',
    description: 'Description',
    value: 'Value',
    start_time: 'Start Time',
    end_time: 'End Time',
    max_discount: 'Max Discount',
    usage_limit: 'Usage Limit',
    user_limit: 'User Limit',
    area_name: 'Area Name',
    valid_from: 'Valid From',
    valid_until: 'Valid Until',
    expired: 'Expired',
    cashback_voucher: 'Cashback Voucher',
    validity: 'Validity',
    used: 'Used',
    no_vouchers_yet: 'No vouchers yet',
    create_first_voucher: 'Create your first one!',
    cashback_to_wallet: 'Cashback to Wallet?',
    target_order_number: 'Target Order Number',
  },
  id: {
    // Nav & Sidebar
    dashboard: 'Dasbor',
    users: 'Pengguna',
    user: 'Pengguna',
    no_users_found: 'Pengguna tidak ditemukan',
    wallet: 'Dompet',
    therapists: 'Terapis',
    therapist: 'Terapis',
    orders: 'Pesanan',
    services: 'Layanan',
    vouchers: 'Voucher',
    total_vouchers: 'total voucher',
    reports: 'Laporan',
    settings: 'Pengaturan',
    logout: 'Keluar',
    pijat_admin: 'Admin Pijat',
    on_demand_platform: 'Platform On-Demand',

    // Common Buttons & Actions
    save_changes: 'Simpan Perubahan',
    add_new: 'Tambah Baru',
    add_therapist: 'Tambah Terapis',
    add_service: 'Tambah Layanan',
    add_voucher: 'Tambah Voucher',
    update_therapist: 'Perbarui Terapis',
    update_service: 'Perbarui Layanan',
    update_voucher: 'Perbarui Voucher',
    update: 'Perbarui',
    total_orders_count: 'total pesanan',
    auto_refresh: 'Segarkan otomatis setiap 5 dtk',
    all: 'Semua',
    orders_monitor: 'Monitor Pesanan',
    edit: 'Ubah',
    delete: 'Hapus',
    cancel: 'Batal',
    refresh: 'Segarkan',
    search: 'Cari',
    all_status: 'Semua Status',
    filter: 'Filter',

    // Table Headers & Content
    name: 'Nama',
    phone: 'Telepon',
    email: 'Email',
    gender: 'Jenis Kelamin',
    status: 'Status',
    actions: 'Aksi',
    rating: 'Rating',
    date: 'Tanggal',
    registered: 'Terdaftar',
    amount: 'Jumlah',
    customer: 'Pelanggan',
    verified: 'Terverifikasi',
    bio: 'Bio',
    skills: 'Keahlian',
    device_id_label: 'Device ID',
    active_status: 'Status Aktif',
    therapist_detail: 'Detail Terapis',
    no_skills: 'Tidak ada keahlian khusus',
    close: 'Tutup',
    no_therapists: 'Terapis tidak ditemukan',
    showing: 'Menampilkan',
    of: 'dari',
    previous: 'Sebelumnya',
    next: 'Berikutnya',
    page: 'Halaman',

    // Form Labels
    full_name: 'Nama Lengkap',
    phone_number: 'Nomor Telepon',
    email_address: 'Alamat Email',
    brief_description: 'Deskripsi Singkat',
    verify_immediately: 'Verifikasi terapis ini segera',
    female: 'Perempuan',
    male: 'Laki-laki',

    // Status Labels
    online: 'Online',
    offline: 'Offline',
    busy: 'Sibuk',
    pending: 'Menunggu',
    accepted: 'Diterima',
    on_the_way: 'Dalam Perjalanan',
    in_progress: 'Sedang Berlangsung',
    completed: 'Selesai',
    cancelled: 'Dibatalkan',
    rejected: 'Ditolak',

    // Dashboard Overview
    total_orders: 'Total Pesanan',
    active_therapists: 'Terapis Aktif',
    new_users: 'Pengguna Baru',
    recent_orders: 'Pesanan Terbaru',
    no_orders_yet: 'Belum ada pesanan',
    quick_actions: 'Aksi Cepat',
    vs_last_month: 'vs bulan lalu',
    real_time_overview: 'Ringkasan platform Anda secara real-time',
    total_revenue: 'Total Pendapatan',
    total_users: 'Total Pengguna',
    total_therapists: 'Total Terapis',
    active_orders: 'Pesanan Aktif',
    online_therapists: 'Terapis Online',
    todays_orders: 'Pesanan Hari Ini',
    todays_revenue: 'Pendapatan Hari Ini',
    x_today: 'hari ini',
    x_online: 'online',
    platform_performance: 'Analisis performa platform',
    daily_revenue: 'Pendapatan Harian (30 Hari Terakhir)',
    daily_orders: 'Pesanan Harian (30 Hari Terakhir)',
    status_breakdown: 'Rincian Status Pesanan',
    services_configured: 'layanan dikonfigurasi',
    edit_service: 'Ubah Layanan',
    service_name: 'Nama Layanan',
    duration_min: 'Durasi (menit)',
    price_idr: 'Harga (IDR)',
    is_active_label: 'Layanan ini',
    active: 'Aktif',
    inactive: 'Nonaktif',
    saving: 'Menyimpan...',
    service_updated: 'Layanan diperbarui!',
    service_created: 'Layanan dibuat!',
    delete_confirm: 'Hapus item ini?',
    failed_to_delete: 'Gagal menghapus',
    edit_voucher: 'Ubah Voucher',
    voucher_code: 'Kode Voucher',
    voucher_type: 'Tipe Voucher',
    percentage: 'Persentase',
    fixed_amount: 'Jumlah Tetap',
    discount_value: 'Nilai Diskon',
    min_order: 'Minimal Order',
    direct: 'Diskon Langsung',
    new_user: 'Hanya Pengguna Baru',
    repeat_order: 'Order Berulang',
    happy_hour: 'Happy Hour',
    location: 'Berdasarkan Lokasi',
    user_tier: 'Tier Pengguna',
    cashback: 'Cashback',
    wallet_balance: 'Saldo Dompet',
    registered_date: 'Tgl Bergabung',
    therapist_level: 'Level Terapis',
    account_status: 'Status Akun',
    skills_specialization: 'Keahlian & Spesialisasi',
    short_bio: 'Biodata Singkat',
    voucher_updated: 'Voucher diperbarui!',
    voucher_created: 'Voucher dibuat!',
    revenue: 'Pendapatan',
    unlimited: 'Tak Terbatas',
    no_cap: 'Tanpa Batas',
    type: 'Tipe',
    manage_service_types: 'Kelola Tipe Service',
    add_service_type: 'Tambah Tipe Service Baru',
    list_service_types: 'Daftar Tipe Service',
    service_type_desc: 'Atur daftar kategori layanan & tipe harganya',
    edit_service_type: 'Sedang Mengedit Tipe Service',

    // Settings
    general: 'Umum',
    language: 'Bahasa',
    platform_name: 'Nama Platform',
    support_email: 'Email Dukungan',
    commission_rate: 'Tarif Komisi (%)',
    notifications: 'Notifikasi',
    security: 'Keamanan',
    integrations: 'Integrasi',
    verify_therapist: 'Verifikasi Terapis',
    not_verified: 'Belum Terverifikasi',
    tier: 'Tier',
    bronze: 'Bronze',
    silver: 'Silver',
    gold: 'Gold',
    diamond: 'Diamond',
    description: 'Deskripsi',
    value: 'Nilai',
    start_time: 'Jam Mulai',
    end_time: 'Jam Selesai',
    max_discount: 'Maksimal Diskon',
    usage_limit: 'Kuota Penggunaan',
    user_limit: 'Batas Per Pengguna',
    area_name: 'Nama Area',
    valid_from: 'Berlaku Dari',
    valid_until: 'Berlaku Hingga',
    expired: 'Kedaluwarsa',
    cashback_voucher: 'Voucher Cashback',
    validity: 'Masa Berlaku',
    used: 'Digunakan',
    no_vouchers_yet: 'Belum ada voucher',
    create_first_voucher: 'Buat voucher pertama Anda!',
    cashback_to_wallet: 'Cashback ke Dompet?',
    target_order_number: 'Nomor Order Target',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('id');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang) setLanguageState(savedLang);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}
